### ISSUE TITLE
Migrate LSBC issuer to use Aries Askar and the Shared Components

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP-DevOps#83]
Updated: Changed to be specific to the LSBC Issuer.  This is a precursor task to updating the LSBC Issuer to a soon-to-be-released version of ACA-Py.

- [x] `Dev`
  - [x] Configuration Update
  - [x] ACA-Py Upgrade
  - [x] Secure Storage Database Upgrade
  - [x] Migration to Askar
  - [x] Run tagged upgrade to fix legacy IssuerRevRegRecords
  - [x] Switch to Askar only image
  - [x] Connect to Sovrin TestNet Endorser Agent (https://github.com/bcgov/DITP-DevOps/issues/85)
  - [x] Rotate revocation registries - `UUHA3oknprvKrpa7a6sncK:3:CL:209518:default`
- [x] `Test`
  - [x] Configuration Update
  - [x] ACA-Py Upgrade
  - [x] Secure Storage Database Upgrade
  - [x] Migration to Askar  
  - [x] Run tagged upgrade to fix legacy IssuerRevRegRecords
  - [x] Switch to Askar only image
  - [x] Connect to Sovrin TestNet Endorser Agent (https://github.com/bcgov/DITP-DevOps/issues/85)
  - [x] Rotate revocation registries - `AuJrigKQGRLJajKAebTgWu:3:CL:209526:default`
- [x] `Prod`
  - [x] Configuration Update
  - [x] ACA-Py Upgrade
  - [x] Secure Storage Database Upgrade
  - [x] Migration to Askar  
  - [x] Run tagged upgrade to fix legacy IssuerRevRegRecords
  - [x] Switch to Askar only image
  - [x] Connect to Sovrin MainNet Endorser Agent (https://github.com/bcgov/DITP-DevOps/issues/86)
  - [x] Rotate revocation registries - `4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default`

Related tickets:
- https://github.com/bcgov/DITP-DevOps/issues/101
- https://github.com/bcgov/DITP-DevOps/issues/102

Tagged Upgrade Command:
- https://github.com/hyperledger/aries-cloudagent-python/pull/2486
- https://github.com/hyperledger/aries-cloudagent-python/issues/2485
```
$(echo aca-py upgrade --force-upgrade --named-tag fix_issue_rev_reg --wallet-name "$(echo ${AGENT_WALLET_NAME} | tr '[:upper:]' '[:lower:]' | sed "s~-~_~g")" --wallet-key "${WALLET_ENCRYPTION_KEY}" --wallet-storage-config "$(eval echo \"${WALLET_STORAGE_CONFIGURATION}\")" --wallet-storage-creds "$(eval echo \"${WALLET_STORAGE_CREDENTIALS}\")" --seed "${INDY_WALLET_SEED}");
```

**Comment by WadeBarnes** [comment]
I've updated the google spreadsheet with the agent version and storage type information, which will make this easier.

**Comment by WadeBarnes** [comment]
Migrating to askar should be performed at the same time as an agent and wallet upgrade.
Steps:
- Upgrade the environment's backup container to support Postgres v14
- Convert agent to upgraded configuration - See https://github.com/bcgov/trust-over-ip-configurations/blob/main/openshift/templates/issuer-agent/issuer-agent-deploy.yaml
- Upgrade the agent to the latest version of `ACA-Py`
- Upgrade to Postgres v14
  - Sample data
  - Shutdown agent(s)
  - Backup existing wallet
  - Delete data directory from database pod
  - Upgrade database image
  - Wait for rollout to complete
  - Start the database pod
  - Start and stop agent to create the database (required for restore).
  - Restore from backup
  - Start agent
  - Check data
- Migrate to Askar
  - Sample data
  - Shutdown agent(s)
  - Backup existing wallet
  - Deploy the askar upgrade container into the environment being upgraded.
  - Update the network policies to allow the upgrade container to connect with the wallet database
  - Run the `askar-upgrade` script.  For example:
    ```
    askar-upgrade \
      --strategy dbpw \
      --uri postgres://<username>:<password>@<hostname>:<port>/<dbname> \
      --wallet-name <wallet name> \
      --wallet-key <wallet key>
    ```
  - Switch the agent's `ACAPY_WALLET_TYPE` to `askar`
  - Wait for the agent rollout to complete
  - Start agent
  - Check data
  - Test

**Comment by WadeBarnes** [comment]
Refer to https://github.com/bcgov/DITP-DevOps/issues/18 for a link to the spreadsheet listing the agent deployments and their associated storage type.

**Comment by swcurran** [comment]
Looks like IDIM is already using Askar, so the focus is only on the migration of LSBC. Propose making this task ONLY about the migration of LSBC, and we open new tasks for the migration of other deployments.

**Comment by swcurran** [comment]
Updated the title of the ticket and description to talk only about LSBC.  We need to be ready to upgrade the LSBC issuer to a new version of ACA-Py when it becomes available, which will have fixes that are only available using Askar.

**Comment by WadeBarnes** [comment]
Migrate to using Askar only images at the same time.

**Comment by WadeBarnes** [comment]
LSBC `test`:
- Upgraded to `py3.9-indy-1.16.0-0.10.3-pre0` images for testing.
- Upgraded DB to Porstgres v14.
- Migrated to Askar storage
- Ran tagged upgrade script - Seemingly no records to be upgraded.  Output:
  ```
  $ $(echo aca-py upgrade --force-upgrade --named-tag fix_issue_rev_reg --wallet-name "$(echo ${AGENT_WALLET_NAME} | tr '[:upper:]' '[:lower:]' | sed "s~-~_~g")" --wallet-key "${WALLET_ENCRYPTION_KEY}" --wallet-storage-config "$(eval echo \"${WALLET_STORAGE_CONFIGURATION}\")" --wallet-storage-creds "$(eval echo \"${WALLET_STORAGE_CREDENTIALS}\")" --seed "${INDY_WALLET_SEED}");
  $ 
  ```

**Comment by WadeBarnes** [comment]
I plan to switch the migrated instances to the Askar only images and rotate the registries once the official ACA-Py `0.10.3` release is available.  Then proceed with the upgrade and migration of `prod`.

**Comment by WadeBarnes** [comment]
LSBC `dev` has been connected to the Sovrin TestNet endorser and its RevRegs have been rotated.

I rotated the RevRegs twice as a test, since the rotate only generated a single RevReg.

First rotation:
Active:
```
{
  "rev_reg_ids": [
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:f1399a43-9046-44ce-9a69-94203beab9ca"
  ]
}
```
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341405
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341406

Decommissioned: 
```
{
  "rev_reg_ids": [
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:d41706d2-c3ef-4297-878a-b9c30318a89e",
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:c6f98707-dbca-4ecc-92d6-5eb0837f20dc"
  ]
}
```

Second rotation:
Active:
```
{
  "rev_reg_ids": [
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:a7a6ebb0-cfed-42fe-8c98-b061c5be81e3"
  ]
}
```
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341407
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341408

Decommissioned: 
```
{
  "rev_reg_ids": [
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:f1399a43-9046-44ce-9a69-94203beab9ca",
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:d41706d2-c3ef-4297-878a-b9c30318a89e",
    "UUHA3oknprvKrpa7a6sncK:4:UUHA3oknprvKrpa7a6sncK:3:CL:209518:default:CL_ACCUM:c6f98707-dbca-4ecc-92d6-5eb0837f20dc"
  ]
}
```

@usingtechnology, can you confirm this behavior would be due to only having a single RevReg active to start with.  I forgot to double check before I rotated.

**Comment by WadeBarnes** [comment]
LSBC `test` has been connected to the Sovrin TestNet endorser and its RevRegs have been rotated.

State Before Rotation:
Active:
```
{
  "rev_reg_ids": [
    "AuJrigKQGRLJajKAebTgWu:4:AuJrigKQGRLJajKAebTgWu:3:CL:209526:default:CL_ACCUM:7aa88d5c-e1e8-488c-a0a5-63aee1b0ae66"
  ]
}
```

Full:
```
{
  "rev_reg_ids": [
    "AuJrigKQGRLJajKAebTgWu:4:AuJrigKQGRLJajKAebTgWu:3:CL:209526:default:CL_ACCUM:1608bebf-71c5-469a-990c-64c47c6e853f"
  ]
}
```

State After Rotation:
Active:
```
{
  "rev_reg_ids": [
    "AuJrigKQGRLJajKAebTgWu:4:AuJrigKQGRLJajKAebTgWu:3:CL:209526:default:CL_ACCUM:9fc50d37-b15d-47f2-8ada-75c2249abc44"
  ]
}
```
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341409
- https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341410

Decommissioned:
```
{
  "rev_reg_ids": [
    "AuJrigKQGRLJajKAebTgWu:4:AuJrigKQGRLJajKAebTgWu:3:CL:209526:default:CL_ACCUM:1608bebf-71c5-469a-990c-64c47c6e853f",
    "AuJrigKQGRLJajKAebTgWu:4:AuJrigKQGRLJajKAebTgWu:3:CL:209526:default:CL_ACCUM:7aa88d5c-e1e8-488c-a0a5-63aee1b0ae66"
  ]
}
```

@usingtechnology, These results confirm the rotate is only creating new RevRegs for `active` ones.

**Comment by usingtechnology** [comment]
Are you fetching results with `GET /revocation/registries/created?state=`?

Long story short - yes. For each Active registry being rotated out a new one is created/activated. If there is only one then only one will replace it.

The list of decommissioned can appear larger than expected because every call to rotate will mark ALL (except init state) as decommissioned - so the currently active plus: generated, posted, and full.

**Comment by WadeBarnes** [comment]
> Are you fetching results with `GET /revocation/registries/created?state=`?

Yes, and filtered by the cred_def_id.

**Comment by WadeBarnes** [comment]
Notified LSBC that the updates are complete for `dev` and `test`.

**Comment by WadeBarnes** [comment]
LSBC `prod` has been upgraded to ACA-Py 0.10.3 and Postgres v14, migrated to Askar only images, connected to the Sovrin MainNet endorser, and its RevRegs have been rotated.

State Before Rotation:
Active:
```
{
  "rev_reg_ids": [
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:4ae1cc6c-f6bd-486c-8057-88f2ce74e960",
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:60cd8717-2543-4b67-bccd-6cbedcff6b31"
  ]
}
```

State After Rotation:
Active:
```
{
  "rev_reg_ids": [
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:521a117c-c68f-4622-949e-48c853b33ee8",
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:bb1863ef-7891-4e21-89dc-4af5b99d18c6"
  ]
}
```
- https://indyscan.io/tx/SOVRIN_MAINNET/domain/157677
- https://indyscan.io/tx/SOVRIN_MAINNET/domain/157678
- https://indyscan.io/tx/SOVRIN_MAINNET/domain/157679
- https://indyscan.io/tx/SOVRIN_MAINNET/domain/157680

Decommissioned:
```
{
  "rev_reg_ids": [
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:4ae1cc6c-f6bd-486c-8057-88f2ce74e960",
    "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:60cd8717-2543-4b67-bccd-6cbedcff6b31"
  ]
}
```
